title: Linear Algebra Workshop
logo: /assets/img/logo.gif
description: Monday, August 1 (8:00 AM - 11:00 AM PDT) & Tuesday, August 2, 2022 (8:00 AM - 11:00 AM PDT)
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
